export const SEQUELIZE = 'SEQUELIZE';

export const CONFIG_REPOSITORY = 'CONFIG_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const SESSION_PARTICIPANTS_REPOSITORY = 'SESSION_PARTICIPANTS_REPOSITORY';
