export const SEQUELIZE = 'SEQUELIZE';

export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
